
service: api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - sqs:SendMessage
       - sqs:ReceiveMessage
       - sqs:DeleteMessage
       - sqs:GetQueueAttributes
      Resource: arn:aws:sqs:us-west-2:156326229501:WeatherQueue

functions:
  enqueue:
    handler: handler.enqueue
    events:
      - http:
          path: forecast
          method: get

  dequeue:
    handler: handler.dequeue
    events:
      - sqs:
          arn: arn:aws:sqs:us-west-2:156326229501:WeatherQueue
          batchSize: 1


